# Generated by Django 3.0.5 on 2020-04-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('ptcgo_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('series', models.CharField(max_length=25)),
                ('total_cards', models.IntegerField()),
                ('release_date', models.DateField(null=True)),
                ('symbol_url', models.URLField()),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('national_pokedex_number', models.IntegerField(null=True)),
                ('image_url', models.URLField()),
                ('image_url_hi_res', models.URLField()),
                ('subtype', models.CharField(max_length=50)),
                ('supertype', models.CharField(max_length=50)),
                ('hp', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('artist', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('set_code', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=20)),
                ('evolves_from', models.CharField(max_length=50)),
                ('card_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Card.CardSet')),
            ],
        ),
    ]
