# Generated by Django 3.0.5 on 2020-04-30 18:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='card',
            managers=[
                ('cards', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cardset',
            managers=[
                ('card_sets', django.db.models.manager.Manager()),
            ],
        ),
    ]
