# Generated by Django 3.0.5 on 2020-04-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0002_auto_20200430_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='total_cards',
            field=models.IntegerField(null=True),
        ),
    ]
