# Generated by Django 3.0.5 on 2020-04-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0003_auto_20200430_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='evolves_from',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
